package com.lz.art.dao;

import com.lz.art.pojo.Crawler;
import com.lz.art.pojo.CrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	int countByExample(CrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	int deleteByExample(CrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	int insert(Crawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	int insertSelective(Crawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */List<Crawler> selectByExample(CrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	Crawler selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */int updateByExampleSelective(@Param("record") Crawler record,@Param("example") CrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */int updateByExample(@Param("record") Crawler record,@Param("example") CrawlerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Crawler record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crawler
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Crawler record);
}