package com.lz.art.dao;

import com.lz.art.pojo.Digest;
import com.lz.art.pojo.DigestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DigestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	int countByExample(DigestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	int deleteByExample(DigestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	int insert(Digest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	int insertSelective(Digest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */List<Digest> selectByExample(DigestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	Digest selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */int updateByExampleSelective(@Param("record") Digest record,@Param("example") DigestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */int updateByExample(@Param("record") Digest record,@Param("example") DigestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Digest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table digest
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Digest record);
}