package com.lz.art.dao;

import com.lz.art.pojo.Url;
import com.lz.art.pojo.UrlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated
     */
    int countByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated
     */
    int deleteByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated
     */
    int insert(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated
     */
    int insertSelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated
     */
    List<Url> selectByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Url record, @Param("example") UrlExample example);
}