package com.lz.art.pojo;

public class Crawler {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.scope
	 * @mbggenerated
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.start_url
	 * @mbggenerated
	 */
	private String startUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.start_url_template
	 * @mbggenerated
	 */
	private String startUrlTemplate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.target_url_template
	 * @mbggenerated
	 */
	private String targetUrlTemplate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.content_grab_expression
	 * @mbggenerated
	 */
	private String contentGrabExpression;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.author_grab_expression
	 * @mbggenerated
	 */
	private String authorGrabExpression;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.date_grab_expression
	 * @mbggenerated
	 */
	private String dateGrabExpression;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.starts_grab_expression
	 * @mbggenerated
	 */
	private String startsGrabExpression;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crawler.status
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.id
	 * @return  the value of crawler.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.id
	 * @param id  the value for crawler.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.name
	 * @return  the value of crawler.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.name
	 * @param name  the value for crawler.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.scope
	 * @return  the value of crawler.scope
	 * @mbggenerated
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.scope
	 * @param scope  the value for crawler.scope
	 * @mbggenerated
	 */
	public void setScope(String scope) {
		this.scope = scope == null ? null : scope.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.start_url
	 * @return  the value of crawler.start_url
	 * @mbggenerated
	 */
	public String getStartUrl() {
		return startUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.start_url
	 * @param startUrl  the value for crawler.start_url
	 * @mbggenerated
	 */
	public void setStartUrl(String startUrl) {
		this.startUrl = startUrl == null ? null : startUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.start_url_template
	 * @return  the value of crawler.start_url_template
	 * @mbggenerated
	 */
	public String getStartUrlTemplate() {
		return startUrlTemplate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.start_url_template
	 * @param startUrlTemplate  the value for crawler.start_url_template
	 * @mbggenerated
	 */
	public void setStartUrlTemplate(String startUrlTemplate) {
		this.startUrlTemplate = startUrlTemplate == null ? null : startUrlTemplate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.target_url_template
	 * @return  the value of crawler.target_url_template
	 * @mbggenerated
	 */
	public String getTargetUrlTemplate() {
		return targetUrlTemplate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.target_url_template
	 * @param targetUrlTemplate  the value for crawler.target_url_template
	 * @mbggenerated
	 */
	public void setTargetUrlTemplate(String targetUrlTemplate) {
		this.targetUrlTemplate = targetUrlTemplate == null ? null : targetUrlTemplate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.content_grab_expression
	 * @return  the value of crawler.content_grab_expression
	 * @mbggenerated
	 */
	public String getContentGrabExpression() {
		return contentGrabExpression;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.content_grab_expression
	 * @param contentGrabExpression  the value for crawler.content_grab_expression
	 * @mbggenerated
	 */
	public void setContentGrabExpression(String contentGrabExpression) {
		this.contentGrabExpression = contentGrabExpression == null ? null : contentGrabExpression.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.author_grab_expression
	 * @return  the value of crawler.author_grab_expression
	 * @mbggenerated
	 */
	public String getAuthorGrabExpression() {
		return authorGrabExpression;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.author_grab_expression
	 * @param authorGrabExpression  the value for crawler.author_grab_expression
	 * @mbggenerated
	 */
	public void setAuthorGrabExpression(String authorGrabExpression) {
		this.authorGrabExpression = authorGrabExpression == null ? null : authorGrabExpression.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.date_grab_expression
	 * @return  the value of crawler.date_grab_expression
	 * @mbggenerated
	 */
	public String getDateGrabExpression() {
		return dateGrabExpression;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.date_grab_expression
	 * @param dateGrabExpression  the value for crawler.date_grab_expression
	 * @mbggenerated
	 */
	public void setDateGrabExpression(String dateGrabExpression) {
		this.dateGrabExpression = dateGrabExpression == null ? null : dateGrabExpression.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.starts_grab_expression
	 * @return  the value of crawler.starts_grab_expression
	 * @mbggenerated
	 */
	public String getStartsGrabExpression() {
		return startsGrabExpression;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.starts_grab_expression
	 * @param startsGrabExpression  the value for crawler.starts_grab_expression
	 * @mbggenerated
	 */
	public void setStartsGrabExpression(String startsGrabExpression) {
		this.startsGrabExpression = startsGrabExpression == null ? null : startsGrabExpression.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crawler.status
	 * @return  the value of crawler.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crawler.status
	 * @param status  the value for crawler.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}