package com.lz.art.pojo;

public class Digest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column digest.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column digest.article_id
	 * @mbggenerated
	 */
	private String articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column digest.digest
	 * @mbggenerated
	 */
	private String digest;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column digest.id
	 * @return  the value of digest.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column digest.id
	 * @param id  the value for digest.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column digest.article_id
	 * @return  the value of digest.article_id
	 * @mbggenerated
	 */
	public String getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column digest.article_id
	 * @param articleId  the value for digest.article_id
	 * @mbggenerated
	 */
	public void setArticleId(String articleId) {
		this.articleId = articleId == null ? null : articleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column digest.digest
	 * @return  the value of digest.digest
	 * @mbggenerated
	 */
	public String getDigest() {
		return digest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column digest.digest
	 * @param digest  the value for digest.digest
	 * @mbggenerated
	 */
	public void setDigest(String digest) {
		this.digest = digest == null ? null : digest.trim();
	}
}