package com.lz.art.pojo;

import java.util.Date;

public class Reviews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviews.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviews.review
	 * @mbggenerated
	 */
	private String review;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviews.reviewer
	 * @mbggenerated
	 */
	private String reviewer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviews.date
	 * @mbggenerated
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviews.helpful_count
	 * @mbggenerated
	 */
	private Integer helpfulCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviews.starts
	 * @mbggenerated
	 */
	private Float starts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviews.id
	 * @return  the value of reviews.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviews.id
	 * @param id  the value for reviews.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviews.review
	 * @return  the value of reviews.review
	 * @mbggenerated
	 */
	public String getReview() {
		return review;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviews.review
	 * @param review  the value for reviews.review
	 * @mbggenerated
	 */
	public void setReview(String review) {
		this.review = review == null ? null : review.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviews.reviewer
	 * @return  the value of reviews.reviewer
	 * @mbggenerated
	 */
	public String getReviewer() {
		return reviewer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviews.reviewer
	 * @param reviewer  the value for reviews.reviewer
	 * @mbggenerated
	 */
	public void setReviewer(String reviewer) {
		this.reviewer = reviewer == null ? null : reviewer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviews.date
	 * @return  the value of reviews.date
	 * @mbggenerated
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviews.date
	 * @param date  the value for reviews.date
	 * @mbggenerated
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviews.helpful_count
	 * @return  the value of reviews.helpful_count
	 * @mbggenerated
	 */
	public Integer getHelpfulCount() {
		return helpfulCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviews.helpful_count
	 * @param helpfulCount  the value for reviews.helpful_count
	 * @mbggenerated
	 */
	public void setHelpfulCount(Integer helpfulCount) {
		this.helpfulCount = helpfulCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviews.starts
	 * @return  the value of reviews.starts
	 * @mbggenerated
	 */
	public Float getStarts() {
		return starts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviews.starts
	 * @param starts  the value for reviews.starts
	 * @mbggenerated
	 */
	public void setStarts(Float starts) {
		this.starts = starts;
	}
}